module.exports = (sequelize, DataTypes) =>
  sequelize.define('UploadedDocumentUrls', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      _autoGenerated: true,
    },
    application_id: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    uploaded_url: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    createdAt: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    filename: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    presigned_url: {
      type: DataTypes.STRING,
      allowNull: true,
    },
  })
