module.exports = function(sequelize, DataTypes) {

    return sequelize.define('UserDetails', {

        id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            _autoGenerated: true
        },
        first_name: {
            type: DataTypes.STRING
        },
        last_name: {
            type: DataTypes.STRING
        },
        telephone: {
            type: DataTypes.STRING
        },
        email: {
            type: DataTypes.STRING
        },
        application_id: {
            type: DataTypes.INTEGER
        }
    });
};